### ISSUE TITLE
Encoder (pulses/rotation) ?

### ISSUE THREAD

**Issue by da198273** [UCLAdmaFABLAB/encoder-and-stepper-demo#1]
E6B2-CWZ3E has many different models with high pulse number and specifications.

The document description does not specify which encoder pulse number is used.
Therefore, I would like to ask about the pulse number specifications of the encoder?

Thanks you.

**Comment by auzal** [comment]
Hello, 

I believe we're using a 1024 pulses per rotation model. There are variables in the code to adjust to whatever resolution your encoder has.
